ALTER TABLE FILM_GENRES ALTER COLUMN id RESTART WITH 1;
ALTER TABLE FILM_LIKES ALTER COLUMN id RESTART WITH 1;
ALTER TABLE FILMS ALTER COLUMN id RESTART WITH 1;
ALTER TABLE FRIENDS ALTER COLUMN id RESTART WITH 1;
ALTER TABLE GENRE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE MPA_RATING ALTER COLUMN id RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN id RESTART WITH 1;

DELETE FROM FILM_GENRES;
DELETE FROM FILM_LIKES;
DELETE FROM FILMS;
DELETE FROM FRIENDS;
DELETE FROM GENRE;
DELETE FROM MPA_RATING;
DELETE FROM USERS;

INSERT INTO GENRE(NAME)
VALUES ('Комедия');

INSERT INTO GENRE(NAME)
VALUES ('Драма');

INSERT INTO GENRE(NAME)
VALUES ('Мультфильм');

INSERT INTO GENRE(NAME)
VALUES ('Триллер');

INSERT INTO GENRE(NAME)
VALUES ('Документальный');

INSERT INTO GENRE(NAME)
VALUES ('Боевик');

INSERT INTO MPA_RATING(MPA_RATING, DESCRIPTION)
VALUES ('G', 'у фильма нет возрастных ограничений');

INSERT INTO MPA_RATING(MPA_RATING, DESCRIPTION)
VALUES ('PG', 'детям рекомендуется смотреть фильм с родителями');

INSERT INTO MPA_RATING(MPA_RATING, DESCRIPTION)
VALUES ('PG-13', 'детям до 13 лет просмотр не желателен');

INSERT INTO MPA_RATING(MPA_RATING, DESCRIPTION)
VALUES ('R', 'лицам до 17 лет просматривать фильм можно только в присутствии взрослого,');

INSERT INTO MPA_RATING(MPA_RATING, DESCRIPTION)
VALUES ('NC-17', 'лицам до 18 лет просмотр запрещён');
